[area]
name = "Rakghoul Tunnels"
id = 137438993429

[[boss]]
id = "eyeless"
name = "The Eyeless"
difficulties = ["story", "veteran"]

[[boss.entities]]
name = "The Eyeless"
ids = [3328380611067904, 25425000358450]
is_boss = true
is_kill_target = true

[[boss.phases]]
id = "eyeless_kite"
name = "The Eyeless"
start_trigger = { type = "any_of", conditions = [
  { type = "combat_start" },
] }