# ═══════════════════════════════════════════════════════════════════════════════
# Objective Meridian - Flashpoint
# ═══════════════════════════════════════════════════════════════════════════════
# Onslaught expansion flashpoint on Corellia. 3 bosses, 1 bonus boss

[area]
name = "Objective Meridian"
id = 833571547775793
area_type = "flashpoint"

# ═══════════════════════════════════════════════════════════════════════════════
# Republic Boss 1: Vulture Squad Armored Units 14 and 02
# ═══════════════════════════════════════════════════════════════════════════════


# ═══════════════════════════════════════════════════════════════════════════════
# Republic Boss 2: Commander Aster
# ═══════════════════════════════════════════════════════════════════════════════


# ═══════════════════════════════════════════════════════════════════════════════
# Republic Boss 3: Darth Malgus
# ═══════════════════════════════════════════════════════════════════════════════


# ═══════════════════════════════════════════════════════════════════════════════
# Republic Bonus Boss: Lord Feng and Darth Yun
# ═══════════════════════════════════════════════════════════════════════════════


# ═══════════════════════════════════════════════════════════════════════════════
# Imperial Boss 1: R10-X6 Droid (Spider Tank)
# ═══════════════════════════════════════════════════════════════════════════════
[[boss]]
id = "r10-x6"
name = "R10-X6 Droid"
difficulties = ["story", "veteran", "master"]

[[boss.entities]]
name = "R10-X6 Droid"
ids = [4256467936538624]
is_boss = true
is_kill_target = true

# ═══════════════════════════════════════════════════════════════════════════════
# Imperial Boss 2: Master Jakir Halcyon and Seldin
# ═══════════════════════════════════════════════════════════════════════════════
[[boss]]
id = "jakir_and_seldin"
name = "Master Jakir Halcyon and Seldin"
difficulties = ["story", "veteran", "master"]

[[boss.entities]]
name = "Master Jakir Halcyon"
ids = [4257442166734848]
is_boss = true
is_kill_target = true

[[boss.entities]]
name = "Seldin"
ids = [4257455051636736]
is_boss = true
is_kill_target = true

# ═══════════════════════════════════════════════════════════════════════════════
# Imperial Boss 3: Tau Idair
# ═══════════════════════════════════════════════════════════════════════════════
[[boss]]
id = "tau_idair"
name = "Tau Idair"
difficulties = ["story", "veteran", "master"]

[[boss.entities]]
name = "Tau Idair"
ids = [4257463641571328]
is_boss = true
is_kill_target = true

# ═══════════════════════════════════════════════════════════════════════════════
# Imperial Bonus Boss: Commander Rasha
# ═══════════════════════════════════════════════════════════════════════════════