[area]
name = "Hive of the Mountain Queen"
id = 945872057669593

[[boss]]
id = "mutated_geonosian_queen"
name = "Mutated Geonosian Queen"
difficulties = ["story", "veteran"]

[[boss.entities]]
name = "Mutated Geonosian Queen"
ids = [4204768687816704]
is_boss = true
is_kill_target = true